name = "push-delivery"
main = "index.js"
compatibility_date = "2026-01-11"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "CONTENT_DB"
database_name = "jeffharr-is-content"
database_id = "efe5518b-5617-4ee8-992a-5c84f4cfe900"

[[queues.consumers]]
queue = "push-delivery"
max_batch_size = 5
max_batch_timeout = 5
max_retries = 5
dead_letter_queue = "push-delivery-dlq"
