name = "read-later-sync"
main = "index.js"
compatibility_date = "2026-01-11"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "CONTENT_DB"
database_name = "jeffharr-is-content"
database_id = "efe5518b-5617-4ee8-992a-5c84f4cfe900"

[[r2_buckets]]
binding = "CONTENT_ASSETS"
bucket_name = "jeffharr-is-content-assets"

[browser]
binding = "BROWSER"

[[queues.consumers]]
queue = "read-later-sync"
max_batch_size = 5
max_batch_timeout = 5

[[queues.producers]]
binding = "READ_LATER_SYNC_QUEUE"
queue = "read-later-sync"

[[queues.producers]]
binding = "PUSH_DELIVERY_QUEUE"
queue = "push-delivery"
